version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: ninjavaz/measuremed-app:latest
    container_name: measuremed_app_container
    command: python measuremed/manage.py runserver 0.0.0.0:8000
    