version: '3.3'

services:
    app:
      image: ninjavaz/notifymed-app:1.0
      ports:
        - "8000:80"
    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379" 
    django-q:
      image: ninjavaz/notifymed-djangoq:1.0