CREATE SCHEMA "notifymed";

CREATE TYPE "notifymed"."user_type" AS ENUM (
  'doctor',
  'patient'
);

CREATE TABLE "notifymed"."users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "created_at" timestamp,
  "user_type" notifymed.user_type
);

CREATE TABLE "notifymed"."doctors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar
);

CREATE TABLE "notifymed"."patients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar
);

CREATE TABLE "notifymed"."notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic" varchar,
  "message" varchar,
  "type" varchar,
  "send_by_email" boolean,
  "is_sent" boolean,
  "created_at" timestamp,
  "planned_on" timestamp
);

CREATE INDEX ON "notifymed"."notifications" ("id", "created_at", "planned_on");

ALTER TABLE "notifymed"."users" ADD FOREIGN KEY ("id") REFERENCES "notifymed"."patients" ("id");

ALTER TABLE "notifymed"."users" ADD FOREIGN KEY ("id") REFERENCES "notifymed"."doctors" ("id");

CREATE TABLE "notifymed"."doctors_patients" (
  "doctors_id" int,
  "patients_id" int,
  PRIMARY KEY ("doctors_id", "patients_id")
);

ALTER TABLE "notifymed"."doctors_patients" ADD FOREIGN KEY ("doctors_id") REFERENCES "notifymed"."doctors" ("id");

ALTER TABLE "notifymed"."doctors_patients" ADD FOREIGN KEY ("patients_id") REFERENCES "notifymed"."patients" ("id");


CREATE TABLE "notifymed"."doctors_notifications" (
  "doctors_id" int,
  "notifications_id" int,
  PRIMARY KEY ("doctors_id", "notifications_id")
);

ALTER TABLE "notifymed"."doctors_notifications" ADD FOREIGN KEY ("doctors_id") REFERENCES "notifymed"."doctors" ("id");

ALTER TABLE "notifymed"."doctors_notifications" ADD FOREIGN KEY ("notifications_id") REFERENCES "notifymed"."notifications" ("id");


CREATE TABLE "notifymed"."patients_notifications" (
  "patients_id" int,
  "notifications_id" int,
  PRIMARY KEY ("patients_id", "notifications_id")
);

ALTER TABLE "notifymed"."patients_notifications" ADD FOREIGN KEY ("patients_id") REFERENCES "notifymed"."patients" ("id");

ALTER TABLE "notifymed"."patients_notifications" ADD FOREIGN KEY ("notifications_id") REFERENCES "notifymed"."notifications" ("id");

