# Generated by Django 4.1.3 on 2022-12-03 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='plannedOnDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
