# Generated by Django 4.1.4 on 2022-12-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_measure_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='name',
        ),
    ]
