# Generated by Django 4.1.3 on 2022-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_notification_plannedondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdAtDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
