# Generated by Django 4.1.4 on 2022-12-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_measure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patient'),
        ),
    ]
