# Generated by Django 4.1.3 on 2022-12-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
